# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
# Windows
  bin = "tmp\\main.exe"
# not Windows
  # bin = "tmp/main"
# Windows
  cmd = "go build -o tmp\\main.exe ."
# not Windows
  # cmd = "go build -o ./tmp/main ."
  delay = 2000
  exclude_dir = ["assets", "tmp", "vendor", "public", "release", "test", "storage"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
# Windows
  full_bin = "tmp\\main.exe"
# not Windows
  # full_bin = "./tmp/main"
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
